CC=gcc
CC_FLAGS=
EXTRA_FLAGS=-g
#LIBS=-lm -lsocket -lnsl
LIBS=-lsocket -lnsl
OBJS=op.o socket.o

SRC=op.c socket.c

.c.o:
	$(CC) $(CC_FLAGS) $(EXTRA_FLAGS) -c $*.c
   
op: 	$(OBJS)
	$(CC) $(CC_FLAGS) $(EXTRA_FLAGS) $(OBJS) -o op $(LIBS)

depend:
	makedepend $(SRC)
     
clean:
	rm *.o;

# DO NOT DELETE THIS LINE -- make depend depends on it.
				      

