all: compound factorial fsa hanoi swap
clean:
	rm -f compound factorial fsa hanoi swap
compound:
	gcc compound.c -o compound
factorial:
	gcc factorial.c -o factorial
fsa:
	gcc fsa.c -o fsa
hanoi:
	gcc hanoi.c -o hanoi
improved_bubble:
	gcc improved_bubble.c -o improved_bubble
sort:
	gcc sort.c -o sort
swap:
	gcc swap.c -o swap
time:
	gcc time.c -o time
format:
	clang-format -i *.c
tidy:
	/opt/homebrew/Cellar/llvm/17.0.6_1/bin/clang-tidy avg.c
