all: compound factorial fsa hanoi swap
clean:
	rm -f compound factorial fsa hanoi swap
compound:
	gcc compound.c -o compound
factorial:
	gcc factorial.c -o factorial
fsa:
	gcc fsa.c -o fsa
hanoi:
	gcc hanoi.c -o hanoi
improved_bubble:
	gcc improved_bubble.c -o improved_bubble
sort:
	gcc sort.c -o sort
swap:
	gcc swap.c -o swap
time:
	gcc time.c -o time
