all: average counter list roach
average:
	gcc average.c -o average
counter:
	gcc counter.c -o counter
list:
	gcc list.c -o list
roach:
	gcc roach.c -o roach
trapezoid:
	gcc trapezoid.c -o trapezoid
clean:
	rm average counter list roach
