all: array list queue stack tree

clean:
	rm -f array list queue stack tree

array: array.c
	gcc -o array array.c

list: list.c
	gcc -o list list.c
queue: queue.c
	gcc -o queue queue.c

stack: stack.c
	gcc -o stack stack.c

tree: tree.c
	gcc -o tree tree.c
