; dos.h

DOS_SERVICE	equ	21H
DOS_READ_CHARACTER equ	01H
DOS_PRINT_STRING equ	09H
DOS_READ	equ	0aH
DOS_TERMINATE	equ	4cH
DOS_GET_INTERRUPT equ	35H
DOS_SET_INTERRUPT equ	25H
TIMER_INTERRUPT	equ	1cH

CR		equ	0dH
LF		equ	0aH

STATUS_OK	equ	00H

TRUE		equ	1
FALSE		equ	0
